version: '3'
services:
  app:
    build: .
    volumes:
      - ./submission:/app/submission
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]